// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:808125533674:web:c4f1267ee09d943ec37693',
    messagingSenderId: '808125533674',
    projectId: 'fluttermobileapp-4c213',
    authDomain: 'fluttermobileapp-4c213.firebaseapp.com',
    storageBucket: 'fluttermobileapp-4c213.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7cNhxWWKHi7c_gXWdZkzFep2UjqJyrHw',
    appId: '1:808125533674:android:a5cfdb058e0b69cfc37693',
    messagingSenderId: '808125533674',
    projectId: 'fluttermobileapp-4c213',
    storageBucket: 'fluttermobileapp-4c213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv5kHBp6_ZgU61uN9M5G1SDYJdQgIYB20',
    appId: '1:808125533674:ios:dce7aa0e96f01f88c37693',
    messagingSenderId: '808125533674',
    projectId: 'fluttermobileapp-4c213',
    storageBucket: 'fluttermobileapp-4c213.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv5kHBp6_ZgU61uN9M5G1SDYJdQgIYB20',
    appId: '1:808125533674:ios:dce7aa0e96f01f88c37693',
    messagingSenderId: '808125533674',
    projectId: 'fluttermobileapp-4c213',
    storageBucket: 'fluttermobileapp-4c213.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUnhLoPczMCCAGrVm7mOovbXxkg0I2A-Y',
    appId: '1:808125533674:web:91764a9740fcc548c37693',
    messagingSenderId: '808125533674',
    projectId: 'fluttermobileapp-4c213',
    authDomain: 'fluttermobileapp-4c213.firebaseapp.com',
    storageBucket: 'fluttermobileapp-4c213.firebasestorage.app',
  );
}
